// Code generated by goctl. DO NOT EDIT!
// Source: token.proto

package server

import (
	"context"

	"moment/rpc-model/token-rpc/internal/logic"
	"moment/rpc-model/token-rpc/internal/svc"
	"moment/rpc-model/token-rpc/types/token"
)

type TokenServer struct {
	svcCtx *svc.ServiceContext
	token.UnimplementedTokenServer
}

func NewTokenServer(svcCtx *svc.ServiceContext) *TokenServer {
	return &TokenServer{
		svcCtx: svcCtx,
	}
}

func (s *TokenServer) GetToken(ctx context.Context, in *token.TokenRequest) (*token.TokenReply, error) {
	l := logic.NewGetTokenLogic(ctx, s.svcCtx)
	return l.GetToken(in)
}
