// Code generated by goctl. DO NOT EDIT!
// Source: moment.proto

package server

import (
	"context"

	"moment/rpc-model/moment-rpc/internal/logic"
	"moment/rpc-model/moment-rpc/internal/svc"
	"moment/rpc-model/moment-rpc/types/moment"
)

type MomentServer struct {
	svcCtx *svc.ServiceContext
	moment.UnimplementedMomentServer
}

func NewMomentServer(svcCtx *svc.ServiceContext) *MomentServer {
	return &MomentServer{
		svcCtx: svcCtx,
	}
}

func (s *MomentServer) CreateMoment(ctx context.Context, in *moment.CreateMomentRequest) (*moment.CreateMomentReply, error) {
	l := logic.NewCreateMomentLogic(ctx, s.svcCtx)
	return l.CreateMoment(in)
}

func (s *MomentServer) GetMoment(ctx context.Context, in *moment.GetMomentRequest) (*moment.GetMomentReply, error) {
	l := logic.NewGetMomentLogic(ctx, s.svcCtx)
	return l.GetMoment(in)
}

func (s *MomentServer) DelMoment(ctx context.Context, in *moment.DelMomentRequest) (*moment.DelMomentReply, error) {
	l := logic.NewDelMomentLogic(ctx, s.svcCtx)
	return l.DelMoment(in)
}
