// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: moment.proto

package moment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMomentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Text  string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *CreateMomentRequest) Reset() {
	*x = CreateMomentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMomentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMomentRequest) ProtoMessage() {}

func (x *CreateMomentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMomentRequest.ProtoReflect.Descriptor instead.
func (*CreateMomentRequest) Descriptor() ([]byte, []int) {
	return file_moment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMomentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMomentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CreateMomentRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CreateMomentReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CreateMomentReply) Reset() {
	*x = CreateMomentReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMomentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMomentReply) ProtoMessage() {}

func (x *CreateMomentReply) ProtoReflect() protoreflect.Message {
	mi := &file_moment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMomentReply.ProtoReflect.Descriptor instead.
func (*CreateMomentReply) Descriptor() ([]byte, []int) {
	return file_moment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMomentReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type GetMomentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GetMomentRequest) Reset() {
	*x = GetMomentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMomentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMomentRequest) ProtoMessage() {}

func (x *GetMomentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMomentRequest.ProtoReflect.Descriptor instead.
func (*GetMomentRequest) Descriptor() ([]byte, []int) {
	return file_moment_proto_rawDescGZIP(), []int{2}
}

func (x *GetMomentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMomentRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetMomentReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title  string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Text   string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Result string `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GetMomentReply) Reset() {
	*x = GetMomentReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMomentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMomentReply) ProtoMessage() {}

func (x *GetMomentReply) ProtoReflect() protoreflect.Message {
	mi := &file_moment_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMomentReply.ProtoReflect.Descriptor instead.
func (*GetMomentReply) Descriptor() ([]byte, []int) {
	return file_moment_proto_rawDescGZIP(), []int{3}
}

func (x *GetMomentReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetMomentReply) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GetMomentReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type DelMomentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *DelMomentRequest) Reset() {
	*x = DelMomentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelMomentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelMomentRequest) ProtoMessage() {}

func (x *DelMomentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moment_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelMomentRequest.ProtoReflect.Descriptor instead.
func (*DelMomentRequest) Descriptor() ([]byte, []int) {
	return file_moment_proto_rawDescGZIP(), []int{4}
}

func (x *DelMomentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DelMomentRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DelMomentReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DelMomentReply) Reset() {
	*x = DelMomentReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelMomentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelMomentReply) ProtoMessage() {}

func (x *DelMomentReply) ProtoReflect() protoreflect.Message {
	mi := &file_moment_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelMomentReply.ProtoReflect.Descriptor instead.
func (*DelMomentReply) Descriptor() ([]byte, []int) {
	return file_moment_proto_rawDescGZIP(), []int{5}
}

func (x *DelMomentReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_moment_proto protoreflect.FileDescriptor

var file_moment_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x55, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2b, 0x0a,
	0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x38, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x52, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x38, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x4d,
	0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x28, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xce, 0x01, 0x0a,
	0x06, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x46, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x3d, 0x0a, 0x09, 0x67, 0x65, 0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x2e, 0x6d,
	0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x47, 0x65, 0x74, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3d,
	0x0a, 0x09, 0x64, 0x65, 0x6c, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x2e, 0x6d, 0x6f,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44,
	0x65, 0x6c, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x2f, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_moment_proto_rawDescOnce sync.Once
	file_moment_proto_rawDescData = file_moment_proto_rawDesc
)

func file_moment_proto_rawDescGZIP() []byte {
	file_moment_proto_rawDescOnce.Do(func() {
		file_moment_proto_rawDescData = protoimpl.X.CompressGZIP(file_moment_proto_rawDescData)
	})
	return file_moment_proto_rawDescData
}

var file_moment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_moment_proto_goTypes = []interface{}{
	(*CreateMomentRequest)(nil), // 0: moment.CreateMomentRequest
	(*CreateMomentReply)(nil),   // 1: moment.CreateMomentReply
	(*GetMomentRequest)(nil),    // 2: moment.GetMomentRequest
	(*GetMomentReply)(nil),      // 3: moment.GetMomentReply
	(*DelMomentRequest)(nil),    // 4: moment.DelMomentRequest
	(*DelMomentReply)(nil),      // 5: moment.DelMomentReply
}
var file_moment_proto_depIdxs = []int32{
	0, // 0: moment.Moment.createMoment:input_type -> moment.CreateMomentRequest
	2, // 1: moment.Moment.getMoment:input_type -> moment.GetMomentRequest
	4, // 2: moment.Moment.delMoment:input_type -> moment.DelMomentRequest
	1, // 3: moment.Moment.createMoment:output_type -> moment.CreateMomentReply
	3, // 4: moment.Moment.getMoment:output_type -> moment.GetMomentReply
	5, // 5: moment.Moment.delMoment:output_type -> moment.DelMomentReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_moment_proto_init() }
func file_moment_proto_init() {
	if File_moment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_moment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMomentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMomentReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMomentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMomentReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelMomentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelMomentReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_moment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moment_proto_goTypes,
		DependencyIndexes: file_moment_proto_depIdxs,
		MessageInfos:      file_moment_proto_msgTypes,
	}.Build()
	File_moment_proto = out.File
	file_moment_proto_rawDesc = nil
	file_moment_proto_goTypes = nil
	file_moment_proto_depIdxs = nil
}
