// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Name string `json:"name"`
	Pwd  string `json:"pwd"`
}

type LoginRes struct {
	Ret    string `json:"result"`
	Reason string `json:"reason"`
}

type RegisterReq struct {
	Name string `json:"name"`
	Pwd  string `json:"pwd"`
}

type RegisterRes struct {
	Ret    string `json:"result"`
	Reason string `json:"reason"`
}
