// Code generated by goctl. DO NOT EDIT.
package types

type GetTokenReq struct {
	UserId string `json:"id"`
}

type GetTokenRep struct {
	Token  string `json:"token"`
	Result string `json:"result"`
}

type CreateMomentReq struct {
	Title string `json:"title"`
	Text  string `json:"text"`
	Token string `json:"token"`
}

type CreateMomentRep struct {
	Result string `json:"result"`
}

type GetMomentReq struct {
	Id    string `json:"id"`
	Token string `json:"token"`
}

type GetMomentRep struct {
	Title  string `json:"title"`
	Text   string `json:"text"`
	Result string `json:"result"`
}

type DelMomentReq struct {
	Id    string `json:"id"`
	Token string `json:"token"`
}

type DelMomentRep struct {
	Result string `json:"result"`
}
