// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"moment/api-model/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/get_token",
				Handler: get_tokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/create_moment",
				Handler: create_momentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/get_moment",
				Handler: get_momentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/del_moment",
				Handler: del_momentHandler(serverCtx),
			},
		},
	)
}
